export * from "./tenancy";
export * from "./platfrom";
export * from "./patients";
export * from "./scheduling";
export * from "./auth";
export * from "./billing";
export * from "./clinical";
export * from "./treatment";
export * from "./inventory"
export * from "./expenses"
export * from "./commision"